import type { TestData } from "../types";

// Test data registry — all 113 tests
const registry: Record<string, () => Promise<{ default: any }>> = {
  "ab-personality": () => import("./ab-personality"),
  "animal-personality": () => import("./animal-personality"),
  "anxiety": () => import("./anxiety"),
  "attachment-style": () => import("./attachment-style"),
  "big-five-aspects": () => import("./big-five-aspects"),
  "big-five": () => import("./big-five"),
  "bodily": () => import("./bodily"),
  "book-personality": () => import("./book-personality"),
  "boundaries": () => import("./boundaries"),
  "burnout": () => import("./burnout"),
  "career-anchor": () => import("./career-anchor"),
  "character-strengths": () => import("./character-strengths"),
  "charisma": () => import("./charisma"),
  "coffee-personality": () => import("./coffee-personality"),
  "color-personality": () => import("./color-personality"),
  "communication-style": () => import("./communication-style"),
  "conflict-resolution": () => import("./conflict-resolution"),
  "consumer-values": () => import("./consumer-values"),
  "creativity": () => import("./creativity"),
  "critical-thinking": () => import("./critical-thinking"),
  "dark-triad": () => import("./dark-triad"),
  "death-anxiety": () => import("./death-anxiety"),
  "decision-style": () => import("./decision-style"),
  "dependency": () => import("./dependency"),
  "depression": () => import("./depression"),
  "diet-attitude": () => import("./diet-attitude"),
  "digital-wellness": () => import("./digital-wellness"),
  "disc": () => import("./disc"),
  "emotion-granularity": () => import("./emotion-granularity"),
  "emotion-regulation": () => import("./emotion-regulation"),
  "emotional-contagion": () => import("./emotional-contagion"),
  "emotional-exhaustion": () => import("./emotional-exhaustion"),
  "emotional-intelligence": () => import("./emotional-intelligence"),
  "emotional-resilience": () => import("./emotional-resilience"),
  "empathy": () => import("./empathy"),
  "enneagram": () => import("./enneagram"),
  "entrepreneurship": () => import("./entrepreneurship"),
  "environmental": () => import("./environmental"),
  "eq": () => import("./eq"),
  "exercise-motivation": () => import("./exercise-motivation"),
  "existential-anxiety": () => import("./existential-anxiety"),
  "family-relations": () => import("./family-relations"),
  "first-impression": () => import("./first-impression"),
  "flow": () => import("./flow"),
  "food-personality": () => import("./food-personality"),
  "friendship": () => import("./friendship"),
  "gratitude": () => import("./gratitude"),
  "happiness": () => import("./happiness"),
  "humor-style": () => import("./humor-style"),
  "interpersonal-attraction": () => import("./interpersonal-attraction"),
  "interpersonal-intel": () => import("./interpersonal-intel"),
  "intimacy": () => import("./intimacy"),
  "intrapersonal": () => import("./intrapersonal"),
  "introversion": () => import("./introversion"),
  "job-satisfaction": () => import("./job-satisfaction"),
  "leadership": () => import("./leadership"),
  "learning-style": () => import("./learning-style"),
  "life-satisfaction": () => import("./life-satisfaction"),
  "listening-skills": () => import("./listening-skills"),
  "locus-control": () => import("./locus-control"),
  "logical-reasoning": () => import("./logical-reasoning"),
  "loneliness": () => import("./loneliness"),
  "love-language": () => import("./love-language"),
  "manipulation": () => import("./manipulation"),
  "mathematical": () => import("./mathematical"),
  "mbti": () => import("./mbti"),
  "mindfulness": () => import("./mindfulness"),
  "minimalism": () => import("./minimalism"),
  "motivation": () => import("./motivation"),
  "movie-personality": () => import("./movie-personality"),
  "music-personality": () => import("./music-personality"),
  "musical": () => import("./musical"),
  "narcissism": () => import("./narcissism"),
  "naturalistic": () => import("./naturalistic"),
  "ocd": () => import("./ocd"),
  "online-social": () => import("./online-social"),
  "org-commitment": () => import("./org-commitment"),
  "party-personality": () => import("./party-personality"),
  "people-pleasing": () => import("./people-pleasing"),
  "perfectionism": () => import("./perfectionism"),
  "persuasion": () => import("./persuasion"),
  "phobia": () => import("./phobia"),
  "post-traumatic-growth": () => import("./post-traumatic-growth"),
  "power-dynamics": () => import("./power-dynamics"),
  "procrastination": () => import("./procrastination"),
  "psychological-capital": () => import("./psychological-capital"),
  "psychological-resilience": () => import("./psychological-resilience"),
  "public-speaking": () => import("./public-speaking"),
  "resilience": () => import("./resilience"),
  "risk-taking": () => import("./risk-taking"),
  "self-compassion": () => import("./self-compassion"),
  "self-efficacy": () => import("./self-efficacy"),
  "self-esteem": () => import("./self-esteem"),
  "self-worth": () => import("./self-worth"),
  "sleep-quality": () => import("./sleep-quality"),
  "social-anxiety": () => import("./social-anxiety"),
  "social-intelligence": () => import("./social-intelligence"),
  "social-media": () => import("./social-media"),
  "social-network": () => import("./social-network"),
  "social-skills": () => import("./social-skills"),
  "spatial": () => import("./spatial"),
  "stress-coping": () => import("./stress-coping"),
  "stress-tolerance": () => import("./stress-tolerance"),
  "stress": () => import("./stress"),
  "tarot-personality": () => import("./tarot-personality"),
  "temperament": () => import("./temperament"),
  "time-management": () => import("./time-management"),
  "travel-style": () => import("./travel-style"),
  "trust": () => import("./trust"),
  "verbal": () => import("./verbal"),
  "work-life-balance": () => import("./work-life-balance"),
  "work-values": () => import("./work-values"),
  "zodiac-match": () => import("./zodiac-match"),
};

export async function loadTestData(type: string): Promise<TestData | null> {
  const loader = registry[type];
  if (!loader) return null;
  try {
    const mod = await loader();
    const data = mod.default as TestData;
    if (!data || !data.questions) {
      console.error('loadTestData: invalid data for', type);
      return null;
    }
    return data;
  } catch (e) {
    console.error('loadTestData error:', type, e);
    return null;
  }
}

export function isTestRegistered(type: string): boolean {
  return type in registry;
}